/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yourmoney;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import server.AllMethods;

/**
 *
 * @author Admin
 */
public class Register extends javax.swing.JFrame {
    
    AllMethods med = null;

    /**
     * Creates new form Register
     */
    public Register() {
        
        initComponents();
        try {
            med = (AllMethods) Naming.lookup("rmi://localhost:3006/YourMoney");
            
        } catch (MalformedURLException | NotBoundException | RemoteException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrGender = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtOTP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        REGISTER = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        FUsername = new javax.swing.JTextField();
        FName = new javax.swing.JTextField();
        FAddress = new javax.swing.JTextField();
        FEmail = new javax.swing.JTextField();
        FPassword = new javax.swing.JPasswordField();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        RegisterDone = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FPhone = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        lblDupUsername = new javax.swing.JLabel();
        lblWrongPass = new javax.swing.JLabel();
        lblNullName = new javax.swing.JLabel();
        lblNullAddress = new javax.swing.JLabel();
        lblDupEmail = new javax.swing.JLabel();
        lblNullPhone = new javax.swing.JLabel();
        lblNonGender = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbBoxDay = new javax.swing.JComboBox<>();
        cbBoxMonth = new javax.swing.JComboBox<>();
        cbBoxYear = new javax.swing.JComboBox<>();
        lblWrongDOB = new javax.swing.JLabel();

        jLabel2.setText("OTP");

        txtOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOTPActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setBackground(new java.awt.Color(65, 59, 59));

        jPanel1.setBackground(new java.awt.Color(65, 59, 59));

        REGISTER.setForeground(new java.awt.Color(255, 255, 255));
        REGISTER.setText("REGISTER");
        REGISTER.setMaximumSize(new java.awt.Dimension(893, 859));

        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");

        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name");

        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Gender");

        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address");

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");

        FUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FUsernameMouseClicked(evt);
            }
        });

        FName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FNameMouseClicked(evt);
            }
        });
        FName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                FNameInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        FAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FAddressMouseClicked(evt);
            }
        });

        FEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FEmailMouseClicked(evt);
            }
        });

        FPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FPasswordMouseEntered(evt);
            }
        });

        Male.setBackground(new java.awt.Color(65, 59, 59));
        GrGender.add(Male);
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setBackground(new java.awt.Color(65, 59, 59));
        GrGender.add(Female);
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");

        RegisterDone.setText("Register");
        RegisterDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDoneActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Click here to login");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        FPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FPhoneMouseClicked(evt);
            }
        });

        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone");

        lblDupUsername.setForeground(new java.awt.Color(255, 0, 0));
        lblDupUsername.setText(" ");

        lblWrongPass.setForeground(new java.awt.Color(255, 0, 0));
        lblWrongPass.setText(" ");

        lblNullName.setForeground(new java.awt.Color(255, 0, 0));
        lblNullName.setText(" ");

        lblNullAddress.setForeground(new java.awt.Color(255, 0, 0));
        lblNullAddress.setText(" ");

        lblDupEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblDupEmail.setText(" ");

        lblNullPhone.setForeground(new java.awt.Color(255, 0, 0));
        lblNullPhone.setText(" ");

        lblNonGender.setForeground(new java.awt.Color(65, 59, 59));
        lblNonGender.setText("jLabel3");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date of birth");

        cbBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbBoxDay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBoxDayItemStateChanged(evt);
            }
        });
        cbBoxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoxDayActionPerformed(evt);
            }
        });

        cbBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));

        cbBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        cbBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoxYearActionPerformed(evt);
            }
        });

        lblWrongDOB.setForeground(new java.awt.Color(255, 0, 0));
        lblWrongDOB.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(REGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FEmail)
                                        .addComponent(lblDupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(43, 43, 43)
                                    .addComponent(FPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(lblNullAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(address)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterDone)
                                    .addComponent(lblNullPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNonGender, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDupUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(gender)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Female))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(Male))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNullName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblWrongDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(cbBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cbBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cbBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(password)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblWrongPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(FPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(REGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDupUsername)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(FPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWrongPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWrongDOB)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Male)
                    .addComponent(Female)
                    .addComponent(gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNonGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address))
                .addGap(5, 5, 5)
                .addComponent(lblNullAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(FEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(FPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNullPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterDone)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed
    public class MailConfig {
        
        Register r = new Register();
        public static final String HOST_NAME = "smtp.gmail.com";
        
        public static final int SSL_PORT = 465; // Port for SSL

        public static final int TSL_PORT = 587; // Port for TLS/STARTTLS

        public static final String APP_EMAIL = "dinhgtce140538@fpt.edu.vn"; // your email

        public static final String APP_PASSWORD = "3135134162313Vn"; // your password

    }
    
    public boolean OTP(String toEmail) {
        
        String password = "";
        
        Properties props = new Properties();
        String Capital_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        
        String numbers = "0123456789";
        
        String values = Capital_chars
                + numbers;

        // Using random method 
        Random rndm_method = new Random();
        
        for (int i = 0; i < 6; i++) {
            // Use of charAt() method : to get character value 
            // Use of nextInt() as it is scanning the value as int 
            password += values.charAt(rndm_method.nextInt(values.length()));
            
        }
        
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", OTP.MailConfig.HOST_NAME);
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.port", OTP.MailConfig.TSL_PORT);

        // get Session
        Session session = Session.getDefaultInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(OTP.MailConfig.APP_EMAIL, OTP.MailConfig.APP_PASSWORD);
            }
        });

        // compose message
        try {
            MimeMessage message = new MimeMessage(session);
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
            message.setSubject("Welcome to YourMoney");
            message.setText("you are completed to create account YourMoney, Please to comfirm email by enter OTP code: " + password);

            // send message
            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Message sent successfully");
            while (true) {
                
                String str = JOptionPane.showInputDialog(this, "Enter OTP code");
                if (str.equalsIgnoreCase(password)) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong OTP");
                }
            }
        } catch (MessagingException e) {
            System.out.println(e);
        }
        return false;
    }
    
    public String generateCode() {
        String numbers = "0123456789";
        String code = "30062000";
        Random rndm_method = new Random();
        for (int i = 0; i <= 3; i++) {
            // Use of charAt() method : to get character value 
            // Use of nextInt() as it is scanning the value as int 
            code += numbers.charAt(rndm_method.nextInt(numbers.length()));
        }
        return code;
    }
    
    public boolean checkUser(String user, String pass, String mail, String gend, String addre, String nm, String phone, String dob) {
        CheckInput check = new CheckInput();
        int counterror = 0;
        
        if (user.isEmpty()) {
            lblDupUsername.setText("Username cannot null!!!");
            counterror += 1;
        }
        
        if (mail.isEmpty()) {
            lblDupEmail.setText("Email cannot null!!!");
            counterror += 1;
        } else if (check.inputEmail(mail) == null) {
            lblDupEmail.setText("Email dose not exits!!!");
            counterror += 1;
        }
        if (pass.isEmpty()) {
            lblWrongPass.setText("Password cannot null!!!");
            counterror += 1;
        }
        if (gend.isEmpty()) {
            lblNonGender.setText("Please tick gender!!!");
            counterror += 1;
        }
        if (addre.isEmpty()) {
            lblNullAddress.setText("Address cannot null!!!");
            counterror += 1;
        }
        if (nm.isEmpty()) {
            lblNullName.setText("Name cannot null!!!");
            counterror += 1;
        }
        if (phone.isEmpty()) {
            lblNullPhone.setText("Number Phone cannot null!!!");
            counterror += 1;
        } else if (check.inputPhone(phone) == null) {
            lblNullPhone.setText("Number phone dose not exits!!");
            counterror += 1;
        }
        if (!check.inputDOB(dob)) {
            lblWrongDOB.setText("Invalid Date!!!");
        }
        if (counterror > 0) {
            return false;
        }
        
        return true;
    }
    
    public static String encoder(String password) {
        //create varable to store password be encodered
        String generatedPassword = null;
        
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            md.update(password.getBytes());
            byte[] bytes = md.digest();
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                sb.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }
            generatedPassword = sb.toString();
            
        } catch (NoSuchAlgorithmException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return generatedPassword;
    }
    private void RegisterDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDoneActionPerformed
        Register r = new Register();
        Login l = new Login();
        String user = FUsername.getText();
        String pass = String.valueOf(FPassword.getPassword());
        pass = encoder(pass);
        String mail = FEmail.getText();
        String gend = Male.isSelected() ? "Male" : "Female";
        String addre = FAddress.getText();
        String nm = FName.getText();
        String phone = FPhone.getText();
        String dob = cbBoxDay.getSelectedItem() + "/" + cbBoxMonth.getSelectedItem() + "/" + cbBoxYear.getSelectedItem();
        String code = generateCode();
        if (!checkUser(user, pass, mail, gend, addre, nm, phone, dob)) {
            return;
        }
        
        try {
            if (med.Register(user, pass, mail, gend, addre, nm, phone, dob, code)) {
                if (!OTP(mail)) {
                    return;
                }
                JOptionPane.showMessageDialog(this, "Register Complete!!!");
                l.setVisible(true);
                l.pack();
                l.setLocationRelativeTo(null);
                this.dispose();
            } else {
                lblDupUsername.setText("Username already!!!");
                return;
            }
            
        } catch (RemoteException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RegisterDoneActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Login l = new Login();
        l.setVisible(true);
        l.pack();
        l.setLocationRelativeTo(null);
        l.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOTPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtOTP.getText().equals(password)) {
            JOptionPane.showMessageDialog(this, "Login Successful!!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Login Fail!!");
        }    }//GEN-LAST:event_jButton1ActionPerformed

    private void FUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FUsernameMouseClicked
        lblDupUsername.setText(" ");
    }//GEN-LAST:event_FUsernameMouseClicked

    private void FPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPasswordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FPasswordMouseEntered

    private void FPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPasswordMouseClicked
        lblWrongPass.setText(" ");
    }//GEN-LAST:event_FPasswordMouseClicked

    private void FNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FNameMouseClicked
        lblNullName.setText(" ");
    }//GEN-LAST:event_FNameMouseClicked

    private void FAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FAddressMouseClicked
        lblNullAddress.setText(" ");
    }//GEN-LAST:event_FAddressMouseClicked

    private void FEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FEmailMouseClicked
        lblDupEmail.setText(" ");
    }//GEN-LAST:event_FEmailMouseClicked

    private void FPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPhoneMouseClicked
        lblNullPhone.setText(" ");
    }//GEN-LAST:event_FPhoneMouseClicked

    private void FNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_FNameInputMethodTextChanged

    }//GEN-LAST:event_FNameInputMethodTextChanged

    private void cbBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoxYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBoxYearActionPerformed

    private void cbBoxDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoxDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBoxDayActionPerformed

    private void cbBoxDayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBoxDayItemStateChanged
        lblWrongDOB.setText("");
    }//GEN-LAST:event_cbBoxDayItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FAddress;
    private javax.swing.JTextField FEmail;
    private javax.swing.JTextField FName;
    private javax.swing.JPasswordField FPassword;
    private javax.swing.JTextField FPhone;
    private javax.swing.JTextField FUsername;
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup GrGender;
    private javax.swing.JRadioButton Male;
    private javax.swing.JLabel REGISTER;
    private javax.swing.JButton RegisterDone;
    private javax.swing.JLabel address;
    private javax.swing.JComboBox<String> cbBoxDay;
    private javax.swing.JComboBox<String> cbBoxMonth;
    private javax.swing.JComboBox<String> cbBoxYear;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDupEmail;
    private javax.swing.JLabel lblDupUsername;
    private javax.swing.JLabel lblNonGender;
    private javax.swing.JLabel lblNullAddress;
    private javax.swing.JLabel lblNullName;
    private javax.swing.JLabel lblNullPhone;
    private javax.swing.JLabel lblWrongDOB;
    private javax.swing.JLabel lblWrongPass;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
